### ISSUE TITLE
Create Login/Signup 

### ISSUE THREAD

**Issue by BTANISHA11** [BTANISHA11/medcare#1]

**Comment by priyanshuhota** [comment]
Can I take up the issue? @BTANISHA11

**Comment by jinx-vi-0** [comment]
please assign this issue to me.

**Comment by alvin-dennis** [comment]
@BTANISHA11 is it solved? 
If not may i work on this?

**Comment by jinx-vi-0** [comment]
> @BTANISHA11 is it solved? If not may i work on this?

@alvin-dennis sure, please continue.

**Comment by alvin-dennis** [comment]
@BTANISHA11 just Google auth is enough rgt?
