### ISSUE TITLE
[FEAT]: Form to book appointment from services page.

### ISSUE THREAD

**Issue by PranjaliBhardwaj** [BTANISHA11/medcare#13]
@BTANISHA11 I would like to create a form to let users get the services which will overall enhance quality and feature of project. I would like to work on this issue.

**Comment by alvin-dennis** [comment]
@BTANISHA11 If the form is not made, may i?

**Comment by PranjaliBhardwaj** [comment]
no, im working on it. and will create a pull request by today. @BTANISHA11

**Comment by alvin-dennis** [comment]
@PranjaliBhardwaj ok np. If u need help, I am happy to help u.Remember u can link it to firebase

**Comment by BTANISHA11** [comment]
So @alvin-dennis pls work on other issues

**Comment by alvin-dennis** [comment]
@BTANISHA11 yeah np. I just said that I can help him if he wants help
