### ISSUE TITLE
updation of the readme

### ISSUE THREAD

**Issue by alvin-dennis** [BTANISHA11/medcare#20]
@BTANISHA11 I wanted to update the readme to include the configuration data for firebase. pls assign me this issue

**Comment by BTANISHA11** [comment]
Also make readme more better with visualizations.

**Comment by alvin-dennis** [comment]
@BTANISHA11 created a pr. Pls check

**Comment by alvin-dennis** [comment]
@BTANISHA11 add phicsit label?

**Comment by alvin-dennis** [comment]
@BTANISHA11 I think u can close the issue as completed
