### ISSUE TITLE
Add redirects to pages for the footer

### ISSUE THREAD

**Issue by alvin-dennis** [BTANISHA11/medcare#28]
Add terms, faqs, redirect contact us, about us, support us and all that to their respective pages 
@BTANISHA11 pls assign me this issue

**Comment by BTANISHA11** [comment]
Also there are many buttons created on navbar page merge login and signup to one and try to reduce number of buttons on navbar by linking to pages

**Comment by alvin-dennis** [comment]
@BTANISHA11 i will login and signup to one. will check it out

**Comment by alvin-dennis** [comment]
<img width="1229" alt="image" src="https://github.com/BTANISHA11/medcare/assets/134829236/09e44df9-9ffe-40fa-85cb-37e9cf387526">

@BTANISHA11 is this enough?
