### ISSUE TITLE
Make a volunteering page .

### ISSUE THREAD

**Issue by BTANISHA11** [BTANISHA11/medcare#4]

**Comment by alvin-dennis** [comment]
Can u please brief it? @BTANISHA11

**Comment by BTANISHA11** [comment]
> Can u please brief it? @BTANISHA11

it will include:
a form for volunteering by individuals
impact stories
faqs

**Comment by alvin-dennis** [comment]
@BTANISHA11 so just a page with a form that the data will be send to your email and impact stories and faq. I plan to make a item at the navbar and link a page to it

**Comment by BTANISHA11** [comment]
@alvin-dennis this was my idea for the page if you want to do some additions that can optimise the page it would be good.

**Comment by alvin-dennis** [comment]
Well i am no expert but lemme see what i can do... @BTANISHA11

**Comment by alvin-dennis** [comment]
So PHICSIT label is not needed?
@BTANISHA11

**Comment by BTANISHA11** [comment]
it will be counted in your phicsit contributions only

**Comment by alvin-dennis** [comment]
@BTANISHA11 check pr

**Comment by alvin-dennis** [comment]
@BTANISHA11 as i completed this, u can close this issue
