### ISSUE TITLE
Update README for Improved Documentation

### ISSUE THREAD

**Issue by jinx-vi-0** [BTANISHA11/medcare#6]
Clear and well-structured documentation is crucial for users and contributors to understand the project, its purpose, and how to get started

**Comment by alvin-dennis** [comment]
Readme still looks weird.  May i fix it? @BTANISHA11

**Comment by alvin-dennis** [comment]
In some repos, I see PHICSIT label. Is that needed or?

**Comment by BTANISHA11** [comment]
That is not that needed thing

**Comment by jinx-vi-0** [comment]
> Readme still looks weird. May i fix it? @BTANISHA11

Hello @BTANISHA11 , this issue is already assigned to me and will update it soon.

**Comment by alvin-dennis** [comment]
@BTANISHA11 I have created a pull request please check

**Comment by jinx-vi-0** [comment]
@alvin-dennis  this issue is already assigned to me

**Comment by jinx-vi-0** [comment]
hello @BTANISHA11 I have created a pr, please check it and let me know the feedback

**Comment by alvin-dennis** [comment]
By the time I saw it, I asked if I could do it and she assigned me when I asked. I did it and created a pull request

**Comment by jinx-vi-0** [comment]
> By the time I saw it, I asked if I could do it and she assigned me when I asked. I did it and created a pull request

It was assigned to me 4 days ago. There must be some mistake
